// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Service.GroupManager.Postgres;

#nullable disable

namespace Service.GroupManager.Postgres.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220616144524_Deposits")]
    partial class Deposits
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("groups")
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Service.GroupManager.Domain.Models.ClientGroupsProfile", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("text");

                    b.Property<string>("GroupId")
                        .HasColumnType("text");

                    b.HasKey("ClientId");

                    b.HasIndex("GroupId");

                    b.ToTable("profiles", "groups");
                });

            modelBuilder.Entity("Service.GroupManager.Domain.Models.Group", b =>
                {
                    b.Property<string>("GroupId")
                        .HasColumnType("text");

                    b.Property<string>("ConverterProfileId")
                        .HasColumnType("text");

                    b.Property<string>("DepositProfileId")
                        .HasColumnType("text");

                    b.Property<string>("InterestRateProfileId")
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<string>("WithdrawalProfileId")
                        .HasColumnType("text");

                    b.HasKey("GroupId");

                    b.ToTable("groups", "groups");
                });
#pragma warning restore 612, 618
        }
    }
}
